name: Main CI

on: [push, pull_request]

jobs:
  init:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - name: Init Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS `phalcon-migrations`;'

  run:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json
          pecl: true

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Composer dependencies with PHPStan
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        if: always()
        run: vendor/bin/psalm --show-info=false

      - name: Run PHPStan
        if: always()
        run: vendor/bin/phpstan analyse -l 5 src

      - name: Run test suite
        if: always()
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
